### ISSUE TITLE
Check for redundancies

### ISSUE THREAD

**Issue by markski1** [cornzz/sacnr-player-monitor#3]
Application should only notify when a friend recently enters rather than notify per each check.

Probably the best solution to this is to have a second collection that holds "currently online targets" and compare against it for every check. If a new target goes online, add it to the "currently online targets" collection and notify for it. If all targets online are already on the collection, don't do anything. If any target on the "currently online" collection is no longer online after a check, then remove it

**Comment by cornzz** [comment]
I neglected that at first because it seemed not necessary to me, but I'm adding it now.
